# Build
FROM golang:1.16 AS build-env

RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /workspace
COPY . .

RUN go mod download

RUN go build -gcflags="all=-N -l" -o app cmd/*.go

# Run
FROM ubuntu:20.04

EXPOSE 3004
EXPOSE 40000

WORKDIR /
COPY --from=build-env /go/bin/dlv /
COPY --from=build-env /workspace/app /app

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/app"]